/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Session;

import MainPages.ManagerMainPage;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class ManagerSessionPage extends javax.swing.JFrame {

    /**
     * Creates new form EditProductPage
     */
    public ManagerSessionPage() {
        initComponents();
        ViewSessionDetails();
        FillTrainerEmailComboBox();

        tableView.getTableHeader().setFont(new Font("Teko Semibold", Font.BOLD, 18));
    }

    void ViewSessionDetails() {
        String filePath = "D:\\APU Stuff\\Bachelor of Computer Science (Intelligent Systems) [APD2F2202CS(IS)]\\Semester 1\\Object Oriented Development with Java [CT038-3-2-OODJ]\\Group Assignment\\System\\OODJAssignmentRedo\\SessionDetails\\SessionDetails.txt";
        File file = new File(filePath);

        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            DefaultTableModel model = (DefaultTableModel) tableView.getModel();
            Object[] lines = br.lines().toArray();

            for (int i = 0; i < lines.length; i++) {
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }

            br.close();

        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerSessionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ManagerSessionPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void FillTrainerEmailComboBox() {

        String filePath = "D:\\APU Stuff\\Bachelor of Computer Science (Intelligent Systems) [APD2F2202CS(IS)]\\Semester 1\\Object Oriented Development with Java [CT038-3-2-OODJ]\\Group Assignment\\System\\OODJAssignmentRedo\\UserDetails\\TrainerEmail.txt";
        File file = new File(filePath);

        try {
            BufferedReader BR = new BufferedReader(new FileReader(file));
            Object[] lines = BR.lines().toArray();

            for (int i = 0; i < lines.length; i++) {
                String line = lines[i].toString();
                ComboBoxTEmail.addItem(line);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManagerSessionPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void ExportToSessionDetails() {
        String filePath = "D:\\APU Stuff\\Bachelor of Computer Science (Intelligent Systems) [APD2F2202CS(IS)]\\Semester 1\\Object Oriented Development with Java [CT038-3-2-OODJ]\\Group Assignment\\System\\OODJAssignmentRedo\\SessionDetails\\SessionDetails.txt";
        File file = new File(filePath);

        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            for (int i = 0; i < tableView.getRowCount(); i++) {
                for (int j = 0; j < tableView.getColumnCount(); j++) {
                    bw.write(tableView.getValueAt(i, j).toString() + " ");
                }
                bw.newLine();
            }

            bw.close();
            fw.close();

        } catch (IOException ex) {
            Logger.getLogger(ManagerSessionPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();
        lblTEmail = new javax.swing.JLabel();
        lblCName = new javax.swing.JLabel();
        lblFeedbackID = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblCContactNumber = new javax.swing.JLabel();
        txtCContactNumber = new javax.swing.JTextField();
        txtCName = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        txtFeedbackID = new javax.swing.JTextField();
        ComboBoxTEmail = new javax.swing.JComboBox<>();
        txtSessionID = new javax.swing.JTextField();
        lblSession = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APU Gym Centre");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableView.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Customer Contact Number", "Trainer Email", "Time", "Feedback ID", "Session ID"
            }
        ));
        tableView.setGridColor(new java.awt.Color(0, 0, 0));
        tableView.setSelectionBackground(new java.awt.Color(102, 204, 255));
        tableView.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tableView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableView);
        if (tableView.getColumnModel().getColumnCount() > 0) {
            tableView.getColumnModel().getColumn(0).setResizable(false);
            tableView.getColumnModel().getColumn(1).setResizable(false);
            tableView.getColumnModel().getColumn(2).setResizable(false);
            tableView.getColumnModel().getColumn(3).setResizable(false);
            tableView.getColumnModel().getColumn(4).setResizable(false);
            tableView.getColumnModel().getColumn(5).setResizable(false);
        }

        lblTEmail.setFont(new java.awt.Font("Teko SemiBold", 1, 14)); // NOI18N
        lblTEmail.setText("Trainer Email:");

        lblCName.setFont(new java.awt.Font("Teko SemiBold", 1, 14)); // NOI18N
        lblCName.setText("Customer Name:");

        lblFeedbackID.setFont(new java.awt.Font("Teko SemiBold", 1, 14)); // NOI18N
        lblFeedbackID.setText("Feedback ID:");

        btnAdd.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnReturn.setFont(new java.awt.Font("Teko SemiBold", 1, 14)); // NOI18N
        btnReturn.setText("Return");
        btnReturn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblCContactNumber.setFont(new java.awt.Font("Teko SemiBold", 1, 14)); // NOI18N
        lblCContactNumber.setText("Customer Contact Number:");

        txtCContactNumber.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        txtCContactNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCContactNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCContactNumberKeyTyped(evt);
            }
        });

        txtCName.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        txtCName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCNameKeyTyped(evt);
            }
        });

        txtTime.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        txtTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimeKeyTyped(evt);
            }
        });

        lblTime.setFont(new java.awt.Font("Teko SemiBold", 1, 14)); // NOI18N
        lblTime.setText("Time:");

        txtFeedbackID.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        txtFeedbackID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFeedbackID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFeedbackIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFeedbackIDKeyTyped(evt);
            }
        });

        ComboBoxTEmail.setMaximumRowCount(1000000);
        ComboBoxTEmail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null" }));
        ComboBoxTEmail.setToolTipText("");

        txtSessionID.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        txtSessionID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSessionID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSessionIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSessionIDKeyTyped(evt);
            }
        });

        lblSession.setFont(new java.awt.Font("Teko SemiBold", 1, 14)); // NOI18N
        lblSession.setText("Session ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCContactNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFeedbackID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFeedbackID, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTime)
                                    .addComponent(lblTEmail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTime, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
                                    .addComponent(ComboBoxTEmail, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSession)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSessionID, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCName)
                    .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCContactNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTEmail)
                    .addComponent(ComboBoxTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTime)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblFeedbackID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSession)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFeedbackID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSessionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAdd)
                                    .addComponent(btnUpdate)
                                    .addComponent(btnDelete))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnReturn)
                                .addContainerGap())))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        ManagerMainPage MMP = new ManagerMainPage();
        MMP.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (txtCName.getText().equals("") || txtCContactNumber.getText().equals("") || ComboBoxTEmail.getSelectedItem().toString().equals("") || txtTime.getText().equals("") || txtFeedbackID.getText().equals("") || txtSessionID.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter data into the textbox/combo box.");
        } else {
            String data[] = {txtCName.getText(), txtCContactNumber.getText(), ComboBoxTEmail.getSelectedItem().toString(), txtTime.getText(), txtFeedbackID.getText(), txtFeedbackID.getText()};

            DefaultTableModel Table = (DefaultTableModel) tableView.getModel();
            Table.addRow(data);
            JOptionPane.showMessageDialog(this, "Session Added!");

            txtCName.setText("");
            txtCContactNumber.setText("");
            ComboBoxTEmail.setSelectedIndex(-1);
            txtTime.setText("");
            txtFeedbackID.setText("");
            txtSessionID.setText("");

            ExportToSessionDetails();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tableViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableViewMouseClicked
        DefaultTableModel Table = (DefaultTableModel) tableView.getModel();

        String CName = Table.getValueAt(tableView.getSelectedRow(), 0).toString();
        String CContactNumber = Table.getValueAt(tableView.getSelectedRow(), 1).toString();
        String TEmail = Table.getValueAt(tableView.getSelectedRow(), 2).toString();
        String Time = Table.getValueAt(tableView.getSelectedRow(), 3).toString();
        String FeedbackID = Table.getValueAt(tableView.getSelectedRow(), 4).toString();
        String SessionID = Table.getValueAt(tableView.getSelectedRow(), 5).toString();

        txtCName.setText(CName);
        txtCContactNumber.setText(CContactNumber);
        txtTime.setText(Time);
        txtFeedbackID.setText(FeedbackID);
        txtSessionID.setText(SessionID);
    }//GEN-LAST:event_tableViewMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        if (txtCName.getText().equals("") || txtCContactNumber.getText().equals("") || ComboBoxTEmail.getSelectedItem().toString().equals("") || txtTime.getText().equals("") || txtFeedbackID.getText().equals("") || txtSessionID.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter data into the textbox/combo box.");
        } else {
            DefaultTableModel Table = (DefaultTableModel) tableView.getModel();

            int SelectedRow = tableView.getSelectedRow();

            if (SelectedRow >= 0) {

                String CName = txtCName.getText();
                String CContactNumber = txtCContactNumber.getText();
                String TEmail = ComboBoxTEmail.getSelectedItem().toString();
                String Time = txtTime.getText();
                String FeedbackID = txtFeedbackID.getText();
                String SessionID = txtSessionID.getText();

                Table.setValueAt(CName, SelectedRow, 0);
                Table.setValueAt(CContactNumber, SelectedRow, 1);
                Table.setValueAt(TEmail, SelectedRow, 2);
                Table.setValueAt(Time, SelectedRow, 3);
                Table.setValueAt(FeedbackID, SelectedRow, 4);
                Table.setValueAt(SessionID, SelectedRow, 5);

                JOptionPane.showMessageDialog(null, "The session details is updated.", "APU Gym Centre", JOptionPane.PLAIN_MESSAGE);

                txtCName.setText("");
                txtCContactNumber.setText("");
                ComboBoxTEmail.setSelectedIndex(-1);
                txtTime.setText("");
                txtFeedbackID.setText("");
                txtSessionID.setText("");

            }
            ExportToSessionDetails();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel Table = (DefaultTableModel) tableView.getModel();

        if (tableView.getSelectedRowCount() == 1) {
            Table.removeRow(tableView.getSelectedRow());

            txtCName.setText("");
            txtCContactNumber.setText("");
            ComboBoxTEmail.setSelectedIndex(-1);
            txtTime.setText("");
            txtFeedbackID.setText("");
            txtSessionID.setText("");

            ExportToSessionDetails();
        } else {
            if (tableView.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "The database is empty. No session is deleted.");
            } else {
                JOptionPane.showMessageDialog(this, "Please select only one session at a time.");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtCContactNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCContactNumberKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCContactNumberKeyTyped

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMouseClicked

    private void txtCNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNameKeyPressed

    private void txtCNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNameKeyTyped

    private void txtTimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeKeyPressed

    private void txtTimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeKeyTyped

    private void txtFeedbackIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFeedbackIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeedbackIDKeyPressed

    private void txtFeedbackIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFeedbackIDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeedbackIDKeyTyped

    private void txtSessionIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSessionIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSessionIDKeyPressed

    private void txtSessionIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSessionIDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSessionIDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerSessionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerSessionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerSessionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerSessionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerSessionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTEmail;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCContactNumber;
    private javax.swing.JLabel lblCName;
    private javax.swing.JLabel lblFeedbackID;
    private javax.swing.JLabel lblSession;
    private javax.swing.JLabel lblTEmail;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTable tableView;
    private javax.swing.JTextField txtCContactNumber;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtFeedbackID;
    private javax.swing.JTextField txtSessionID;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
